version: "3.8"

services:
  # Base de donn√©es
  postgres:
    image: postgres:15-alpine
    container_name: momentApp_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Stockage de fichiers (MinIO)
  minio:
    image: minio/minio
    container_name: momentApp_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # API pour le code
      - "9001:9001" # Console d'admin Web
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
